# Generated by Django 5.2 on 2025-04-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fb_id', models.IntegerField(null=True)),
                ('last_question', models.IntegerField(default=1)),
                ('last_answer', models.IntegerField(default=1)),
                ('last_score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
