# Generated by Django 5.2 on 2025-04-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_answer',
            new_name='visit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_score',
        ),
    ]
