# Generated by Django 5.2 on 2025-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_last_answer_user_visit_remove_user_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
